version: '3.8'

services:
  octopus-cache:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - octopus_data:/data
    environment:
      - DATA_DIR=/data
      - PASSWORD=password
    restart: unless-stopped

volumes:
  octopus_data:
